### ISSUE TITLE
todo list - 20201127

### ISSUE THREAD

**Issue by Soo77** [Soo77/happy-bin#9]
- [ ]  기부리스트, 디테일 상세하게 

- [ ]  기부 상세에 댓글기능

- [ ]  about 페이지 만들기(옵션)

- [ ]  기부 회원 맵핑테이블에 데이터 들어가게

- [ ]  상점 만들어보기

- [ ]  상점 리뷰 기능

- [ ]  상점 좋아요 기능

**Comment by lima1016** [comment]
👍
